version: "3"
services:
  text-gaming:
    image: text-gaming
    build:
      dockerfile: Dockerfile
      context: .
    container_name: text-gaming
    env_file:
      - src/main/resources/.env
    ports:
      - "8090:8090"
    depends_on:
      - text-gaming-postgres-db
  text-gaming-postgres-db:
    image: postgres
    env_file:
      - src/main/resources/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-back-data:/var/lib/postgresql/data #default path where postgres search for data

volumes:
  postgres-back-data: # volume name
    driver: local # local means that volume is stored on host machine



