application:
  bot:
    token: "${TOKEN}"
    logLevel: "none"
spring:
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: "${DATABASE_URL}"
  username: "${DATABASE_USERNAME}"
  password: "${DATABASE_PASSWORD}"