spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
flyway:
  url: jdbc:postgresql://localhost:49153/postgres
  username: postgres
  password: postgrespw