package ndw.eugene.textgaming.content

enum class Choice {
    TIP_MUSICIANS,
    SAD_SONG,
    FUNNY_SONG,
    EPIC_SONG,

    TEST,
    STARS_TALKING,
    HEARD_COMPANION_STORY,
    BUY_TONIC,
    GIVE_TONIC_TO_SHEPHERD,
    FIORE_APPEARED,
    HEARD_ABOUT_FATHER,
    LOST_NAME,
    TIDY_YOURSELF,
    MERCHANT_STORY,

    WHAT_HAPPENED_TO_THE_LIBRARY,
    WENT_THROUGH_THE_STORM,
    MET_THE_HARPY,
    SPYGLASS,
    PICK_STAR,
    LEFT_SHEPHERD_TO_LIBRARY,
    LEFT_SHEPHERD_TO_HARPIES,
    LEFT_SHEPHERD_TO_JUNGLE,
    BOY_FORCED,
    WAS_IN_HARPY_ENCOUNTER,
    WAS_IN_SHEPHERD_ENCOUNTER,
    LIE_ABOUT_PLANTS,
    LIE_ABOUT_ROCKS,
    LIE_ABOUT_BEETLES,
    GOT_THE_WIZARD,
    GOT_THE_BOY,
    GOT_THE_GIRL,

    //technical
    ASKED_DESTROYED_HOW,
    ASKED_LIBRARIANS,
    EXAMINED_SHELVES,
    EXAMINED_STATUE,
    OFFER_SOLACE,
    OFFER_TRIBUTE,
    OFFER_HOPE,
    RESEARCH,
    CAN_EARN_MONEY,
    HEARD_ABOUT_PROPHET
}