package ndw.eugene.textgaming.content

enum class Choice {
    SAD_SONG,
    FUNNY_SONG,
    EPIC_SONG,

    TEST,
    STARS_TALKING,
    HEARD_COMPANION_STORY,
    OFFER_SOLACE,
    OFFER_TRIBUTE,
    OFFER_HOPE,
    BUY_TONIC,
    GIVE_TONIC_TO_SHEPHERD,
    FIORE_APPEARED,
    HEARD_ABOUT_FATHER,
    LOST_NAME,
    TIDY_YOURSELF,
    MERCHANT_STORY,

    RESEARCH,
    WHAT_HAPPENED_TO_THE_LIBRARY,
    WENT_THROUGH_THE_STORM,
    MET_THE_HARPY,
    SPYGLASS,
    PICK_STAR,
    LEFT_SHEPHERD_TO_LIBRARY,
    LEFT_SHEPHERD_TO_HARPIES,
    LEFT_SHEPHERD_TO_JUNGLE,
    BOY_FORCED,


    //technical
    ASKED_DESTROYED_HOW,
    ASKED_LIBRARIANS,
    EXAMINED_SHELVES,
    TOOK_TABLET,
    EXAMINED_STATUE,
}