CREATE TABLE report (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  location TEXT,
  conversation_id BIGINT NOT NULL,
  report_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);