CREATE TABLE feedback (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  feedback_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);